"""change field name

Revision ID: cac9f187bf39
Revises: 57ad9a8bd264
Create Date: 2025-05-13 15:43:48.703300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac9f187bf39'
down_revision: Union[str, None] = '57ad9a8bd264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=False))
    op.drop_column('users', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fist_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
